apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-de-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-de-scraper
  template:
    metadata:
      labels:
        app: mobile-de-scraper
    spec:
      containers:
        - name: mobile-de-scraper
          image: com.robertciotoiu/mobile-de-crawler.yaml:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-de-scraper-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mobile-de-scraper