apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-de-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-de-crawler
  template:
    metadata:
      labels:
        app: mobile-de-crawler
    spec:
      containers:
        - name: mobile-de-crawler
          image: localhost:5000/com.robertciotoiu/mobile-de-crawler:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest